module.exports = {
    bot: {
        prefix: ".",
        sahipler: ["746066222310883339", "752683146121707663"],
    },
    config: {
        botswid: "",
        footer: "DiscowZombie ❤️ Transsly",
        status: "dnd",
        tag: "",
        tagg: "",
        seslioda: "886090332566077470",
        yassiniri: 14,
    },
    roller: {
        bot: "",
        supheli: "",
        kayitsiz: "",
        erkek1: "",
        erkek2: "", 
        erkek3: "",
        kiz1: "",
        kiz2: "",
        kiz3: "",
        tagli: "",
        yetkilistaff: "",
        registerstaff: "",
        cezali: ""
    },
    kanallar: {
        welcome1: "",
        registerchat: "",
        chat: "",
        kurallar: "",
        public: "",
        /*--------  --------*/
        komutlog: "",
        /*--------  --------*/
        otorollog: "",
        taglilog: "",
        kayitlog: "",
        kayitsizlog: "",
        isimlog: "",
        viplog: "",
    },
    emojiler: {
        discow000: "",
        discow001: "",
        discow002: "",
        discow003: "",
        discow004: "",
        discow005: "",
        discow006: "",
        discow007: "",
        discow008: "",
        discow009: "",
        discow_yetkili: "",
        discow_ses: "",
        discow_kurallar: "",
        discow_carpi: "",
        discow_tik: "",
        discow_kristal: "",
        discow_ok: "",
    }
}